"""Criação da coluna classe na tabela analysis

Revision ID: 0bf956ff1ddb
Revises: b85e1f19ce31
Create Date: 2021-12-16 08:44:30.683294

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0bf956ff1ddb'
down_revision = 'b85e1f19ce31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis', sa.Column('classe', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.drop_constraint('analysis_class_id_fkey', 'analysis', type_='foreignkey')
    op.drop_column('analysis', 'class_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis', sa.Column('class_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('analysis_class_id_fkey', 'analysis', 'classes', ['class_id'], ['id'])
    op.drop_column('analysis', 'classe')
    # ### end Alembic commands ###
