"""Criação da coluna name na tabela analysis

Revision ID: b85e1f19ce31
Revises: 28e350d1ddc7
Create Date: 2021-12-15 09:32:38.500890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b85e1f19ce31'
down_revision = '28e350d1ddc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis', sa.Column('name', sa.String(), nullable=False))
    op.drop_constraint('analysis_batch_key', 'analysis', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('analysis_batch_key', 'analysis', ['batch'])
    op.drop_column('analysis', 'name')
    # ### end Alembic commands ###
